### ISSUE TITLE
[bug] new `builder.pl` crashes at runtime when building environments

### ISSUE THREAD

**Issue by ysndr** [flox/floxpkgs#147] opened 2023-06-30 13:44 UTC
After updating the floxpkgs version used to build managed environments (flox/flox#133) which starts using the builder introduced in #144 flox installs fail within the builder: https://github.com/flox/flox/actions/runs/5422480667/jobs/9861314816?pr=133#step:6:744

```
$ nix log /nix/store/z5445w1v9qp0y4zgk8rqjr8ilxwj0w1w-wrapper.drv

++ /nix/store/v6fpa3626msfmyg22pka0bzcsl49bdm0-perl-5.36.0/bin/perl -w /nix/store/sh2v88m6slc969vyvs7ysniwp53vs07n-builder.pl
warning: creating dangling symlink `/nix/store/q04paxp62wl547ax6s2rrkh6x3lxn5fj-wrapper//manifest.nix' -> `/nix/store/6y5ij59zczwgbs51zkzr7zs4ps6v9j2w-wrapper/manifest.nix' -> `unused'
error: not a directory: `/nix/store/szs36lz492gh28djg0710z2ni4vn60br-jq-1.6'
+ exitHandler
+ exitCode=2
+ set +e
+ '[' -n '' ']'
+ ((  2 != 0  ))
+ runHook failureHook
+ local hookName=failureHook
+ shift
+ local 'hooksSlice=failureHooks[@]'
+ local hook
+ for hook in "_callImplicitHook 0 $hookName" ${!hooksSlice+"${!hooksSlice}"}
+ _eval '_callImplicitHook 0 failureHook'
+ declare -F '_callImplicitHook 0 failureHook'
+ eval '_callImplicitHook 0 failureHook'
++ _callImplicitHook 0 failureHook
++ local def=0
++ local hookName=failureHook
++ declare -F failureHook
++ type -p failureHook
++ '[' -n '' ']'
++ return 0
+ return 0
+ '[' -n '' ']'
+ return 2
```

at what seems to be a missing built of jq

**Comment by aakropotkin** [comment] 2023-07-12 21:30
Moved out of the sprint to focus on other tasks.
This bug blocks the use of `etc-profiles` and prevents us from installing a number of common packages such as `pkg-config`; but if we can avoid installing those in steel-thread flows we can fix this later.

**Comment by limeytexan** [comment] 2023-07-24 18:20
Related? https://github.com/flox/floxpkgs/pull/148

**Comment by limeytexan** [comment] 2023-07-24 19:44
Closing after confirming with @aakropotkin that this was a duplicate of #148, fixed with https://github.com/flox/flox/pull/133, and confirmed that this particular problem is no longer present.  :heavy_check_mark:

**Closed by limeytexan** 2023-07-24 19:44 UTC
